-- Un solo aviso de vencimiento por ciclo, en vez de uno por dia.
--
-- notifyExpiringSoon corre todos los dias a las 03:00 y avisa a quien le vence
-- el plan dentro de 3 dias. Sin una columna que registre el aviso, al usuario
-- le llegaban TRES emails identicos en tres dias seguidos.
--
-- Guarda CUANDO se aviso. El cron compara esa fecha contra planExpiresAt: si
-- el aviso es posterior al arranque del ciclo, ya se aviso por este periodo. Al
-- renovar, planExpiresAt se mueve hacia adelante y el ciclo siguiente vuelve a
-- avisar solo.
--
-- La tabla es "users", no "User": el modelo lleva @@map("users"), igual que
-- casi todos los de este schema.
ALTER TABLE "users" ADD COLUMN "renewalNoticeSentAt" TIMESTAMP(3);
